name: SkinTools
main: skintools\SkinTools
version: 1.0.0
api: 1.12.0
load: POSTWORLD
author: Gamecrafter
description: Have fun with your skins!
website: https://github.com/Gamecrafter/PocketMine-Plugins/tree/master/SkinTools
permissions:
 skintools:
  default: op
  children:
   skintools.command:
    default: op
    children:
     skintools.command.skintools:
      default: op
