name: iManager
main: imanager\iManagerAPI
version: 1.2.0
api: 1.12.0
load: STARTUP
author: Gamecrafter
description: Manage your server like never before!
website: https://github.com/Gamecrafter/PocketMine-Plugins/tree/master/iManager
permissions:
 imanager:
  default: op
  children:
   imanager.command:
    default: op
    children:
     imanager.command.imanager:
      default: op
